# Background and foreground colors
background = #070707
foreground = #F9DEBE

# Standard colors
palette = 0=#070707
palette = 1=#c5836b
palette = 2=#f1b672
palette = 3=#ffde94
palette = 4=#b36673
palette = 5=#ee8d86
palette = 6=#ffd163
palette = 7=#F9DEBE

# Bright colors
palette = 8=#5f5d57
palette = 9=#e79375
palette = 10=#ffc86b
palette = 11=#ffd878
palette = 12=#d37485
palette = 13=#ff9991
palette = 14=#ffe654
palette = 15=#fef2ed
