$color = rgba(7, 7, 7, 1)
$inner_color = rgba(7, 7, 7, 0.66)
$outer_color = rgba(238, 141, 134, 1)
$font_color = rgba(249, 222, 190, 1)
$placeholder_color = rgba(249, 222, 190, 0.7)
$check_color = rgba(255, 209, 99, 1)
