background            #070707
foreground            #F9DEBE

# black
color0  #070707
color8  #5f5d57

# red
color1  #c5836b
color9  #e79375

# green
color2  #f1b672
color10 #ffc86b

# yellow
color3  #ffde94
color11 #ffd878

# blue
color4  #b36673
color12 #d37485

# magenta
color5  #ee8d86
color13 #ff9991

#cyan
color6  #ffd163
color14 #ffe654

#white
color7  #F9DEBE
color15 #fef2ed


